FROM debian:stretch

RUN apt-get update -y
RUN apt-get install -y git make gcc libtool zlib1g-dev openssl patch vim-common libluajit-5.1-dev pkg-config autoconf libssl-dev

WORKDIR /opt/sonic
VOLUME /opt/sonic/bin

COPY . /opt/sonic

RUN ./configure --enable-build-libuv CFLAGS='-I/opt/sonic/deps/include -I/usr/include/luajit-2.0 -DOPENSSL_NO_STDIO -O3'

CMD make
